name: CI/CD Pipelin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/nodejs-web-app:${{ github.sha }} .
          docker tag your-dockerhub-username/nodejs-web-app:${{ github.sha }} your-dockerhub-username/nodejs-web-app:latest
          docker push your-dockerhub-username/nodejs-web-app:${{ github.sha }}
          docker push your-dockerhub-username/nodejs-web-app:latest
